version: "3.7"
services:
    node:
        build: .
        container_name: "node"
        volumes:
            - .:/home/app
            - /home/app/node_modules
        ports:
            - '8080:8080'
        command:
            "npx http-server -p 8080"